server:
  port: 5000
app:
  host: ${API_GATEWAY}
spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/customers
    username: ${DB_USERNAME}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: ${PLATFORM}
