server:
  port: 7000
app:
  message: message succesfuly sent
spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/billing
    username: ${DB_USERNAME}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: ${PLATFORM}

  rabbitmq:
    host: ${HOST}
    password: ${PASSWORD}
    port: 15672
    username: ${USERNAME}
    exchange: user.exchange
    routingkey: user.routingkey

